### ISSUE TITLE
Suppress verbose progress output

### ISSUE THREAD

**Issue by a-x-** [enb/enb#442]
Add `enb make --slient # -s` option
Show text-based "spinner"

**Comment by a-x-** [comment]
reason: log is useless and it decrease performance

**Comment by blond** [comment]
Link #320 #345

**Comment by blond** [comment]
Maybe `enb make --logger=silent`?

When we can add `enb make --logger=error`, `enb make --logger=warnings` etc.

**Comment by blond** [comment]
> reason: log is useless and it decreases performance

Oh. You can show example?

@a-x- PR welcomes ;)

You can use [logger. setEnabled(false)](https://github.com/enb/enb/blob/master/lib/logger.js#L173-L175) in [API](https://github.com/enb/enb/blob/master/lib/api/make.js#L45).

**Comment by a-x-** [comment]
ok, I'll add it into my todo

**Comment by victor-homyakov** [comment]
Removal of logging for `[isValid]` and `[rebuild]` significantly decreases build time for web4 project:

- build time with logs: 76918ms
- build time without isValid/rebuild logs: 63375ms
