### ISSUE TITLE
NOCOLOR analogue in JS API

### ISSUE THREAD

**Issue by blond** [enb/enb#542]

**Comment by anton-rudeshko** [comment]
Блин, я думал, это ПР :)

**Comment by blond** [comment]
Может просто использовать [supports-color](https://github.com/chalk/supports-color)?

**Comment by anton-rudeshko** [comment]
Можно, вроде не вижу причин против.

**Comment by anton-rudeshko** [comment]
https://github.com/chalk/supports-color/issues/46

**Comment by belozer** [comment]
@blond @anton-rudeshko  Этот тикет случаем не про эту проблему?
![image](https://cloud.githubusercontent.com/assets/1655916/25505902/9abbe170-2bac-11e7-9fb8-1594b54da7e6.png)

**Comment by anton-rudeshko** [comment]
Извини, не уверен, что понимаю, куда указывают стрелки. Это вряд ли "проблема", это просто хотелка, так как цвета можно выключить через CLI, но нельзя через JS API.

**Comment by blond** [comment]
`supports-color` работают из коробки в `chalk`
